### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by dimitsou** [khoih-prog/DDNS_Generic#2]
After filling all the required info (wifi cred & dynu details ) in the example (for generic and the dynu) and then compiled and loading them on esp8266 board it doesn't update the ip  (in the serial it stops in something aboout web server)

**Comment by khoih-prog** [comment]
There is nothing changed in `dynu` [**IP-Update-Protocol**](https://www.dynu.com/DynamicDNS/IP-Update-Protocol), so it's possible there is something wrong in your code / pwd, I don't think there is any issue.
