### ISSUE TITLE
IP lookup fail, due to ipv4bot no longer exist

### ISSUE THREAD

**Issue by kkeonline** [khoih-prog/DDNS_Generic#3]
According to the whatismyipaddress.com website, they are no longer supporting the API for ipv4bot.whatismyipaddress.com

**Comment by khoih-prog** [comment]
Hi @kkeonline 

Thanks for reporting the issue.

I've just successfully modified the library to use another site and the library can now run normally on ESP, WiFi and Ethernet for many boards now.

Will post a new release soon after full tests.

Cheers,

**Comment by khoih-prog** [comment]
Hi,

The new [**DDNS_Generic releases v1.6.0**](https://github.com/khoih-prog/DDNS_Generic/releases/tag/v1.6.0) has just been released. Your contribution has been noted in [**Contributions and Thanks**](https://github.com/khoih-prog/DDNS_Generic#contributions-and-thanks)

---

### Releases v1.6.0

1. Replace deprecated `ipv4bot.whatismyipaddress.com` with `ifconfig.me`
